" set colorscheme
" syntax enable
" set background=light
" colorscheme solarized
" color PaperColor
" color solarized
" color base16-ocean
" colorscheme gruvbox
" color dracula
" colorscheme hybrid_material
" color folds
hi Folded ctermbg=Black
hi MatchParen ctermbg=238
hi Visual ctermbg=237
hi Search ctermbg=242
hi VertSplit ctermbg=102
hi VertSplit ctermfg=234
